linters:
  disable-all: true
  enable:
    ## enabled by default
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code
    - unused # checks for unused constants, variables, functions and types
    - whitespace # detects leading and trailing whitespace
  
   ## disabled by default
    - asasalint # checks for pass []any as any in variadic func(...any)
    - goconst # finds repeated strings that could be replaced by a constant
    - revive # fast, configurable, extensible, flexible, and beautiful linter for Go, drop-in replacement of golint
    - unconvert # Detect unnecessary type conversions
    - unparam # Detect unused function parameters
    - misspell # Fix spelling errors
    - goimports # Ensure standard import formatting/ordering
